### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by autormali** [waynedgrant/meteo-alarm-weather-warnings#1]
It looks like Meteoalarm changed code and this script is not fetching the data anymore.

**Comment by waynedgrant** [comment]
It's working fine for me. If it's still broken for you perhaps provide a little more detail?

**Comment by autormali** [comment]
Simply try to run any example from README.md, you posted :
https://waynedgrant.com/weather/warnings/warnings.json?country=NL&region=014
or
https://waynedgrant.com/weather/warnings/warnings.json?country=UK
above are returning page with error 404 Not Found.

**Comment by autormali** [comment]
OK figured it out. There should be:
https://waynedgrant.com/weather/warnings/meteo-alarm-weather-warnings/warnings.json?country=UK
or
https://waynedgrant.com/weather/warnings/meteo-alarm-weather-warnings/warnings.json?country=NL&region=014

The description is not updated.

**Comment by waynedgrant** [comment]
You were hitting the wrong url because I moved my instance of the service. None of the examples in the README point at my instance, they're all general (just the sample response mentions the service location on my website).

The idea behind open sourcing this this project was to allow people to setup their own instance of meteo-alarm-weather-warnings, not to call mine - I'm paying for the bandwidth. You can expect my instance to be locked down in the coming days.
